Milestone project: Positioning and Floating Elements
ShinobiWarior/TheNewYorkTimes-project pull request #4
Opened 2021-03-24 15:01 UTC by ShinobiWarior

In this project, we cloned The New York Times page.

2021-03-24 18:04 UTC, christianotieno requested changes
## Changes Required ♻️ 
Hello @ShinobiWarior 👋🏾 

Thank you for submitting your `Positioning and Floating Elements` project for the first review. The codebase is clean, DRY for the majority of parts of the codebase saved for a few, and free of commented out code. It is quite commendable how you have strived to keep the repository professional for the majority of parts.  The commit messages were great and deliberate in informing what changes they were introducing to the codebase. The README looks professional. Keep it up 👏🏾 

Before this gets approved, we need to make sure nothing is messed up. Kindly take care of some highlighted issues down below. 👇🏾 

**Kindly note: that as described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have 2 code reviews left for this project. I would urge we try and work on the suggested changes with utmost keenness so as to not miss out on the remaining chances to get our project approved.** 

### Mandatory changes
- [ ] Fix the image not loading error.
- [ ] Aim to remain DRY

### Optional Changes (Nice to have)
- [ ] Implementing the fixed section at bottom of the footer. 

### Happy coding 💻 
#### Christian Otieno (CR)

2021-03-24 18:04 UTC, christianotieno commented on index.html
> +        <img src="img/Bicep2-telescope.png" alt="The Bicep-2 telescope">
##  Fix the image not loading error.
- [x] The image you are referencing appears not to be of the same format. Do you mind fixing this?
Currently, this is whats we have in the `img` directory, which is remotely close to the [image ](https://static01.nyt.com/images/2014/03/18/science/space/18cosmos-2/18cosmos-2-articleLarge.jpg?quality=75&auto=webp&disable=upscale)you are trying to reference here.

|[Source Page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|[Clone Page](https://raw.githack.com/ShinobiWarior/TheNewYorkTimes-project/development/index.html)|
|:--:|:--:|
|![Bicept](https://user-images.githubusercontent.com/22345961/112357286-6af5f900-8ce0-11eb-91e4-f613a80bb016.png)|![Bicept-clone](https://user-images.githubusercontent.com/22345961/112357306-70ebda00-8ce0-11eb-9c7b-f3b9707fa6b9.png)|

2021-03-24 18:04 UTC, christianotieno commented on index.html
> +    </ul>
### Optional Change
- [ ] Do you mind while conducting the above changes, implement the sticky section bottom of the footer that sticks to the bottom of the page as well?
![sticky-footer](https://user-images.githubusercontent.com/22345961/112357427-92e55c80-8ce0-11eb-9ba0-b527f21d13ee.png)

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +.article a:hover {
### Aim to remain DRY
- [x] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#25`, `#197`, & `#300`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +figure {
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#122` & `#156`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +  color: black;
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#187` & `#213`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +}
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#200` & `#423`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +.box-img {
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#38` & `#546`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +  text-decoration: underline;
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#73`, `#193`, `#257`, `#370`,`#526`, & `#599`**

2021-03-24 18:04 UTC, christianotieno commented on style.css
> +  margin-bottom: 5px;
### Aim to remain DRY
- [ ] This rule seems to be repeating more than once and makes you appear as if you are repeating yourself. Do you mind merging these ones so as to make the codebase look neat?

**The repeating rules are on lines `#340` & `#603`**

2021-03-24 18:48 UTC, ShinobiWarior commented on index.html
> +      <img class="img-relative" src="img/inflation.png" alt="Inflation">
I apologize, but I believe that this part is fully implemented. This is not the screenshot from the original page but just the image layer over which I positioned missing text. The image was downloaded from the original site, that's true, but it wasn't a screenshot. This snippet doesn't cover the rest of the code where the text is positioned over the image.  I just want to make sure that there are no misunderstandings. Can you confirm that you want me to change this part of code?

2021-03-24 18:51 UTC, ShinobiWarior commented on index.html
> +    </ul>
Don't mind at all. It will be a nice improvement.

2021-03-24 19:06 UTC, christianotieno commented on index.html
> +      <img class="img-relative" src="img/inflation.png" alt="Inflation">
Thank you for bringing this up. I must have missed it. Do you mind if I deleted this requirement so as to not confuse the next reviewer? Apologies as I had not misled you intentionally.

2021-03-25 10:16 UTC, christianotieno commented on index.html
> +      <img class="img-relative" src="img/inflation.png" alt="Inflation">
Noted ✅

2021-03-25 10:32 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @ShinobiWarior :tada: :clinking_glasses: 

_**Thank you for implementing all the required changes by the last reviewer.**_

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

**Optional Changes / Comments**
- As we have on the original page, you might want to ensure that the top navbar is fixed to the top.
- Also, it will be nice if you can link (wrap the `<a>` tag around) the NYT logo on the top navbar. 

Again, congratulations, you can merge to the default branch.
Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-03-25 11:02 UTC, merged